# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    #paths:
      #- "api/*"
      #- "go.*"
      #- "*.go"
      #- ".github/workflows/go.yml"
  pull_request:
    branches: [ "master" ]
    #paths:
      #- "api/*"
      #- "go.*"
      #- "*.go"
      #- ".github/workflows/go.yml"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Setup Golang caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-

    - name: Build webserver
      run: go build -v ./...

    - name: Test webserver
      run: go test -v ./...
  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: go fmt
      run: go fmt ./...
    - name: Add & Commit
      # You may pin to the exact commit or the version.
      # uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b
      uses: EndBug/add-and-commit@v9.1.1
      with:
        add: .
        commit: --signoff
        push: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
    #- name: Commit and push changes
      #uses: devops-infra/action-commit-push@master
      #with:
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        #commit_prefix: "[GO FMT]"
